# Generated by Django 5.2.13 on 2026-09-16 18:08

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0227_alter_interface_speed_bigint'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('length_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('diameter_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_capacity_percentage', models.PositiveSmallIntegerField(default=40)),
                ('start_object_id', models.PositiveBigIntegerField()),
                ('start_position', models.CharField(blank=True, max_length=50)),
                ('end_object_id', models.PositiveBigIntegerField()),
                ('end_position', models.CharField(blank=True, max_length=50)),
                ('cables', models.ManyToManyField(blank=True, related_name='conduits', to='dcim.cable')),
                ('end_object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('start_object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JunctionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ip_rating', models.CharField(blank=True, max_length=20)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='junction_boxes', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name_plural': 'Junction Boxes',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
