# Generated by Django 5.2.13 on 2026-09-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_infra_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='junctionbox',
            name='terminals_down',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='terminals_left',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='terminals_right',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='terminals_up',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
