# Generated by Django 5.2.13 on 2026-09-22 10:34

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_physical_infra_plugin', '0002_junctionbox_terminals_down_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junctionbox',
            name='terminals_down',
        ),
        migrations.RemoveField(
            model_name='junctionbox',
            name='terminals_left',
        ),
        migrations.RemoveField(
            model_name='junctionbox',
            name='terminals_right',
        ),
        migrations.RemoveField(
            model_name='junctionbox',
            name='terminals_up',
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('junction_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='netbox_physical_infra_plugin.junctionbox')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('junction_box', 'name'),
                'unique_together': {('junction_box', 'name')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
