# Generated by Django 5.2.13

from django.db import migrations, models

def set_sequential_indexes(apps, schema_editor):
    """
    Iterates through existing terminals and assigns a unique, sequential 
    index to each terminal based on its junction box and position.
    """
    Terminal = apps.get_model('netbox_physical_infra_plugin', 'Terminal')
    
    counters = {}
    for term in Terminal.objects.all().order_by('id'):
        key = (term.junction_box_id, term.position)
        
        # Initialize counter for this specific box and position if it doesn't exist
        if key not in counters:
            counters[key] = 1
            
        term.index = counters[key]
        counters[key] += 1
        term.save()

class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_infra_plugin', '0004_remove_conduit_end_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ('junction_box', 'position', 'index', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together=set(),
        ),
        # 1. Add the column with the default value of 1
        migrations.AddField(
            model_name='terminal',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
        # 2. Run the Python function to fix duplicates on existing data
        migrations.RunPython(set_sequential_indexes, reverse_code=migrations.RunPython.noop),
        # 3. Finally, apply the unique constraint now that data is clean
        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together={('junction_box', 'position', 'index')},
        ),
    ]